use_frameworks!

platform :ios, '9.0'

target 'FactoryViewController_Example' do
  pod 'FactoryViewController', :path => '../'

  target 'FactoryViewController_Tests' do
    inherit! :search_paths

    
  end
end
